### PR TITLE
Upgrade to PHPUnit 8.5

### PR DESCRIPTION
**Pull request by hertz1**
This is required in order to run tests with Monolog 2. The changes are described in each commit.

If this PR is accepted, I will open a new one for Monolog 2 support.

### CODE REVIEW

**Comment by bhavinrshah** [comment]
@bhavinrshah : Please review

**Comment by dmnc** [comment]
Hi @hertz1. I can approve but unfortunately do not have permission to release.

@rantonmattei and @mymac80 @glensc are you able to release this or potentially willing to give me release permissions on the repo?

**Review by dmnc — APPROVED** [review]
Tested and all working. As an extreme nitpick, I might suggest adding the `.phpunit.result.cache` file generated by later versions of phpunit to `.gitignore`.

**Review by andymc — APPROVED** [review]

**Comment by dmnc** [comment]
Is anybody able to use the tag successfully? I'm having issues because of the branch alias at https://github.com/theorchard/monolog-cascade/blob/master/composer.json#L43

This stops anything like `dev-master#0.6.0-pre` from working. I can't use `0.6.0@pre` because pre isn't in the [composer list of stabilities](https://getcomposer.org/doc/articles/versions.md#stabilities).

@andymc could we please have a new tag called `0.6.0-beta1`? That should then allow composer to pull it in as `^0.6.0@beta`.

**Pull request merged**
