### PR TITLE
Setting up Travis CI

### PR DESCRIPTION
**Pull request by rantonmattei**
@mortaliorchard @OrCharles

### CODE REVIEW

**Comment by xethorn** [comment]
Some issues with php 5.3.9.

**Comment by rantonmattei** [comment]
Build failed, I think I might not be able to use php 5.3.9 on Travis CI. Will look into this

**Comment by rantonmattei** [comment]
Travis does not support specific version unless it comes directly with the Ubuntu distro used. `5.3.9` is not one of those. So, I changed it to 5.3 which is ok. 5.3.9 is a requirement from a Symfony package because of a bug in Reflection. I'll keep it as long as my tests pass. Composer will enforce 5.3.9 anyway
because of the `"php": ">=5.3.9",` in `composer.json`

**Comment by xethorn** [comment]
R+

**Pull request merged**
