### PR TITLE
Allow symfony 5.x packages

### PR DESCRIPTION
**Pull request by glensc**
Symfony [5.0] was released in November 2019, [5.1] in May 2020.

[5.0]: https://symfony.com/releases/5.0
[5.1]: https://symfony.com/releases/5.1

### CODE REVIEW

**Comment by glensc** [comment]
@rantonmattei why not merge and release?

**Comment by glensc** [comment]
Is this project dead?

**Comment by rantonmattei** [comment]
It is not dead. Unfortunately I not have merge rights. 
CC  @mymac80 @bhavinrshah @andymc

**Review by mymac80 — APPROVED** [review]

**Comment by glensc** [comment]
Without making a new release the merge on its own is useless.

**Comment by mymac80** [comment]
Thanks for being patient. https://github.com/theorchard/monolog-cascade/releases/tag/0.5.3

**Pull request merged**
